[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
colony = "BCVGJ5YoKMftBrt5fgDYhtvY7HVBccFofFiGqJtoRjqE"

[programs.devnet]
colony = "BCVGJ5YoKMftBrt5fgDYhtvY7HVBccFofFiGqJtoRjqE"

[programs.localnet]
colony = "BCVGJ5YoKMftBrt5fgDYhtvY7HVBccFofFiGqJtoRjqE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-deposit = "npx ts-node scripts/test-deposit.ts"
deploy-game = "npx ts-node scripts/deploy-game.ts"
init-game = "npx ts-node scripts/init-game.ts"
check-game = "npx ts-node scripts/check-game.ts"
